# spring.application.name=airport-management

server.port=8080

spring.datasource.url=${AIRPORT_DB_URL:jdbc:h2:file:./target/data/airport-management;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE}
spring.datasource.username=${AIRPORT_DB_USERNAME:sa}
spring.datasource.password=${AIRPORT_DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jackson.serialization.fail-on-empty-beans=false
